/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Page } from "@/Components/Page/Page";
import Anchor from "@/Components/Anchor/Anchor";
import ButtonModal from "@/Components/ButtonModal/ButtonModal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const url = typeof window !== "undefined" ? window.location.href : "";
  console.log("Olá" + url);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Page.Content className="flex bg-white h-screen text-black shadow-2xl">
          <Page.SideBar>
            <nav className="flex flex-col items-center h-screen w-[10rem]">
              <li className="flex justify-center p-5 w-full">
                <img
                  src="https://avatars.githubusercontent.com/u/89848369?v=4"
                  width={100}
                  height={200}
                  className="rounded-full shadow-black shadow-md border-1 border-black"
                  alt="Foto de Perfil do Daniel"
                />
              </li>
              <li className="flex h-[83%] w-full justify-between border flex-col items-center py-5">
                <div className="flex gap-5 flex-col">
                  <Anchor href="/" icon={"Graphic"} />
                  <Anchor href="/Certificados" icon={"File"} />
                  <Anchor href="/Hobbies" icon={"Hobbie"} />
                  <Anchor href="/History" icon={"History"} />
                </div>
                <div className="flex gap-5 flex-col">
                  <ButtonModal>
                    <Anchor href="#" icon={"Gear"} />
                  </ButtonModal>
                </div>
              </li>
            </nav>
          </Page.SideBar>
          <main className="bg-gray-200 w-screen">{children}</main>
        </Page.Content>
      </body>
    </html>
  );
}
